#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

pushd ${OPENSHIFT_REPO_DIR} > /dev/null

# cd $OPENSHIFT_REPO_DIR
# echo '=> Migrate database'
# bundle exec rake db:migrate RAILS_ENV=production
# echo '=> Precombile assets'
# bundle exec rake assets:clean RAILS_ENV=production
# bundle exec rake assets:precompile RAILS_ENV=production

cd $OPENSHIFT_REPO_DIR
echo '=> Bundle gems'
bundle install --without test development --deployment --path vendor/
echo '=> Migrate database'
bundle exec rake db:migrate RAILS_ENV=production
echo '=> Precompile assets'
bundle exec rake assets:precompile RAILS_ENV=production

popd > /dev/null
