development:
  adapter: postgresql
  encoding: unicode
  database: timetrack_development
  pool: 5
  username: timetrack
  password: timetrack
  host: localhost
  port: 5432

test: &test
  adapter: postgresql
  encoding: unicode
  database: timetrack_test
  pool: 5
  username: timetrack
  password: timetrack
  host: localhost
  port: 5432
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: timetrack_production
  pool: 5
  username: timetrack
  password: timetrack
  host: localhost
  port: 5432

cucumber:
  <<: *test
