production:
  sessions:
    default:
      url: <%= ENV['MONGOHQ_URL'] %>
      options:
        consistency: :strong
        raise_not_found_error: false
        skip_version_check: true
        safe: true

development:
  sessions:
    default:
      database: timetrack_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: timetrack_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
