---
chdir: /srv/www/htdocs/timetrack/current
environment: production
address: 0.0.0.0
port: 80
timeout: 10
log: log/thin.log
pid: /var/run/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
servers: 1
daemonize: false
